window.SFP_TRANSLATIONS = {
  ko: {
    navFeatures:"놀이 특징",navPrivacy:"개인정보처리방침",eyebrow:"아이 손끝에서 완성되는 픽셀 놀이",title:"고르고, 두드리고,\n나만의 세상을 만들어요.",intro:"Super Foam Pixel은 폼 블록의 즐거움을 휴대폰과 태블릿에 담은 어린이용 픽셀 조립 놀이입니다.",coming:"Google Play · App Store 출시 준비 중",templates:"다양한 도안",templatesBody:"동물, 과일, 탈것, 감정, 모험 등 아이가 좋아하는 도안을 골라요.",free:"마음대로 만들기",freeBody:"8×8 또는 10×10 격자를 원하는 색으로 자유롭게 채워요.",impact:"톡톡 두드리는 재미",impactBody:"망치, 고양이 발, 로봇 주먹과 귀여운 소리·진동을 골라요.",family:"아이와 보호자를 함께 생각했어요",familyBody:"큰 조작 영역, 자유·엄격 모드, 작은 색상 가이드와 작품 백업을 제공합니다.",local:"작품은 기기에 저장",localBody:"회원가입 없이 바로 놀고, 완성한 작품은 기기에 저장하거나 사진으로 공유할 수 있어요.",tablet:"태블릿에서는 더 섬세하게",tabletBody:"큰 화면에서는 16×16 상세 도안까지 만나 볼 수 있어요.",privacy:"개인정보를 어떻게 다루는지 확인하세요",privacyBody:"앱은 계정을 만들지 않으며 작품은 기본적으로 기기에 저장됩니다. 광고와 선택 기능의 데이터 처리를 투명하게 안내합니다.",privacyButton:"개인정보처리방침 보기",contact:"문의",back:"홈으로",policyTitle:"개인정보처리방침",updated:"시행일: 2026년 8월 31일",policyIntro:"hopalt(이하 ‘개발자’)는 Super Foam Pixel(패키지: com.hopalt.dfblock)을 제공합니다. 이 방침은 앱을 이용할 때 데이터가 어떻게 처리되는지 설명합니다.",policySections:[
      ["1. 핵심 안내","앱은 회원가입, 로그인, 사용자 계정 기능을 제공하지 않습니다. 이름, 이메일, 전화번호, 위치, 연락처, 카메라 또는 마이크 정보를 개발자가 직접 요청하거나 수집하지 않습니다."],
      ["2. 기기에 저장되는 데이터","선택한 언어·음악·가이드·놀이 모드·타격 도구·색상 설정과 완성 작품은 사용자의 기기에 저장됩니다. 개발자는 이 데이터에 원격으로 접근하지 않습니다. 앱 삭제 또는 기기 설정의 앱 데이터 삭제로 제거할 수 있습니다."],
      ["3. 광고와 Kidoz","Kidoz 적용 Android 버전은 Kidoz SDK로 배너 광고를 표시할 수 있습니다. 현재 iOS 버전에는 Kidoz 광고가 없습니다. Kidoz는 행동 기반 맞춤 광고 대신 문맥 기반 광고를 제공합니다. 광고 제공과 운영을 위해 국가 수준의 대략적 위치, 기기·운영체제·언어 정보, 광고 이용 정보 및 짧은 수명의 임의 세션 식별자 등을 처리할 수 있습니다. Kidoz 공식 정책에 따르면 SDK는 광고 식별자를 수집하지 않습니다. 이전 배포 버전에는 기존 광고 SDK가 남아 있을 수 있습니다."],
      ["4. 사진 저장·공유·백업","사용자가 직접 선택한 경우 완성 작품을 사진 보관함에 저장하거나 시스템 공유 메뉴를 통해 다른 앱으로 보낼 수 있습니다. 작품 백업은 JSON 파일로 사용자가 선택한 위치 또는 앱에 공유되며, 개발자의 서버로 자동 업로드되지 않습니다."],
      ["5. 아동의 개인정보","이 앱은 어린이를 포함한 가족 사용자를 위해 설계되었습니다. 개발자는 아동에게 개인정보 입력을 요구하지 않습니다. 보호자는 기기의 앱 데이터와 사진·백업 파일을 관리할 수 있습니다."],
      ["6. 제3자 서비스","앱은 Android 광고에 Kidoz를 사용하며, 사진 저장·공유·파일 선택에는 Apple/Google의 시스템 기능을 사용합니다. Kidoz가 처리하는 데이터의 보관·삭제 및 권리 행사에 관한 자세한 내용은 아래 공식 정책을 확인해 주세요.",{"label":"Kidoz 개인정보처리방침","url":"https://www.kidoz.net/privacy-policy"}],
      ["7. 보관·삭제·보안","기기 내 데이터는 사용자가 삭제할 때까지 보관됩니다. 공유하거나 백업한 파일은 사용자가 선택한 외부 앱 또는 저장 위치의 정책에 따라 보관됩니다."],
      ["8. 국가 간 처리","Kidoz 등 제3자 서비스 제공자는 사용자의 국가 밖에서 정보를 처리할 수 있습니다. 이러한 처리에는 각 제공자의 개인정보 보호조치가 적용됩니다."],
      ["9. 방침 변경 및 문의","앱 기능, 외부 서비스 또는 법적 요구사항이 변경되면 이 방침을 갱신할 수 있습니다. 문의: hopalt@gmail.com"]]
  },
  en: {
    navFeatures:"Features",navPrivacy:"Privacy",eyebrow:"Pixel play made by little hands",title:"Pick, tap, and build\na world of your own.",intro:"Super Foam Pixel brings the fun of foam-block crafts to phones and tablets for young creators.",coming:"Preparing for Google Play · App Store",templates:"Lots of patterns",templatesBody:"Choose animals, fruit, vehicles, emotions, adventures, and more.",free:"Create freely",freeBody:"Fill an 8×8 or 10×10 grid with any colors you like.",impact:"Tap with playful tools",impactBody:"Choose a hammer, cat paw, robot fist, cute sounds, and haptics.",family:"Designed for children and families",familyBody:"Large controls, free and strict modes, color guides, and artwork backup are included.",local:"Artwork stays on your device",localBody:"Start without an account. Save creations locally or export them as pictures to share.",tablet:"More detail on tablets",tabletBody:"Large screens unlock detailed 16×16 patterns.",privacy:"See how privacy is handled",privacyBody:"The app has no account system and stores artwork locally by default. Advertising and optional features are explained clearly.",privacyButton:"Read the Privacy Policy",contact:"Contact",back:"Home",policyTitle:"Privacy Policy",updated:"Effective: August 31, 2026",policyIntro:"hopalt (the “Developer”) provides Super Foam Pixel (package: com.hopalt.dfblock). This policy explains how data is handled when the app is used.",policySections:[
      ["1. Summary","The app has no registration, login, or user-account system. The Developer does not directly request or collect names, email addresses, phone numbers, location, contacts, camera data, or microphone data."],
      ["2. Data stored on the device","Language, music, guide, play-mode, impact-tool and color preferences, plus saved artwork, are stored on the user’s device. The Developer cannot access this data remotely."],
      ["3. Advertising and Kidoz","Android versions with Kidoz integration may display banner ads through the Kidoz SDK. The current iOS version has no Kidoz ads. Kidoz serves contextual rather than behavioral advertising. To deliver and operate ads, it may process country-level approximate location, device, operating-system and language information, ad usage information, and short-lived random session identifiers. According to its policy, the SDK does not collect advertising identifiers. Previously released versions may still contain the former advertising SDK."],
      ["4. Photos, sharing, and backups","Only when the user chooses, completed artwork can be saved to the photo library or sent through the system share sheet. Backup files are not automatically uploaded to the Developer’s servers."],
      ["5. Children’s privacy","The app is designed for families, including children. The Developer does not ask children to enter personal information. Parents and guardians can manage app data and exported files on the device."],
      ["6. Third-party services","The app uses Kidoz for Android advertising and Apple/Google system features for photos, sharing, and file selection. See the official policy below for details about Kidoz data retention, deletion, and privacy rights.",{"label":"Kidoz Privacy Policy","url":"https://www.kidoz.net/privacy-policy"}],
      ["7. Retention, deletion, and security","On-device data remains until the user deletes it. Shared photos and backup files remain according to the policy of the selected destination."],
      ["8. International processing","Third-party providers such as Kidoz may process information outside the user’s country. Their respective privacy safeguards apply."],
      ["9. Changes and contact","This policy may be updated when app features, external services, or legal requirements change. Contact: hopalt@gmail.com"]]
  },
  ja: {
    navFeatures:"あそびの特徴",navPrivacy:"プライバシー",eyebrow:"小さな手から生まれるピクセルあそび",title:"えらんで、トントン。\nじぶんだけの世界をつくろう。",intro:"Super Foam Pixelは、フォームブロック工作の楽しさをスマートフォンとタブレットで体験できる子ども向けピクセルあそびです。",coming:"Google Play · App Store 公開準備中",templates:"たくさんの図案",templatesBody:"どうぶつ、くだもの、のりもの、きもち、ぼうけんなどから選べます。",free:"じゆうにつくる",freeBody:"8×8または10×10のマスを好きな色で自由にぬれます。",impact:"トントンする楽しさ",impactBody:"ハンマー、ねこの手、ロボットパンチと楽しい音・振動を選べます。",family:"子どもと家族のための設計",familyBody:"大きな操作、自由・厳格モード、色ガイド、作品バックアップに対応します。",local:"作品は端末に保存",localBody:"アカウントなしですぐ遊べます。作品を端末や写真として保存・共有できます。",tablet:"タブレットでもっと細かく",tabletBody:"大きな画面では16×16の詳細な図案も楽しめます。",privacy:"プライバシーの取り扱い",privacyBody:"アカウント機能はなく、作品は基本的に端末内に保存されます。広告と任意機能のデータ処理を分かりやすく説明します。",privacyButton:"プライバシーポリシー",contact:"お問い合わせ",back:"ホームへ",policyTitle:"プライバシーポリシー",updated:"施行日：2026年8月31日",policyIntro:"hopalt（以下「開発者」）はSuper Foam Pixel（パッケージ：com.hopalt.dfblock）を提供します。本ポリシーは、アプリ利用時のデータの取り扱いを説明します。",policySections:[
      ["1. 基本方針","本アプリには会員登録、ログイン、ユーザーアカウント機能はありません。開発者は氏名、メールアドレス、電話番号、位置情報、連絡先、カメラ、マイク情報を直接要求・収集しません。"],
      ["2. 端末に保存されるデータ","言語、音楽、ガイド、プレイモード、インパクトツール、色の設定と完成作品は端末内に保存されます。開発者は遠隔でアクセスできません。"],
      ["3. 広告とKidoz","Kidozを導入したAndroid版では、Kidoz SDKによるバナー広告を表示する場合があります。現在のiOS版にはKidoz広告はありません。Kidozは行動ターゲティングではなくコンテキスト広告を提供します。広告の配信・運用のため、国単位のおおよその位置、端末・OS・言語情報、広告利用情報、短期間有効なランダムなセッション識別子などを処理する場合があります。公式ポリシーによるとSDKは広告識別子を収集しません。過去の配信版には以前の広告SDKが残っている場合があります。"],
      ["4. 写真保存・共有・バックアップ","ユーザーが選択した場合のみ、作品を写真ライブラリに保存したり、システム共有から別のアプリへ送信できます。開発者のサーバーへ自動送信されません。"],
      ["5. 子どものプライバシー","本アプリは子どもを含む家族向けに設計されています。子どもに個人情報の入力を求めません。保護者は端末内のアプリデータとファイルを管理できます。"],
      ["6. 第三者サービス","Androidの広告にはKidozを、写真保存・共有・ファイル選択にはApple/Googleのシステム機能を使用します。Kidozによるデータの保存・削除および権利の行使については、以下の公式ポリシーをご確認ください。",{"label":"Kidozプライバシーポリシー","url":"https://www.kidoz.net/privacy-policy"}],
      ["7. 保管・削除・安全管理","端末内データはユーザーが削除するまで保管されます。共有した写真・バックアップは選択した保存先の方針に従います。"],
      ["8. 国外での処理","Kidozなどの第三者サービスは、利用者の居住国以外で情報を処理する場合があります。各提供者のプライバシー保護措置が適用されます。"],
      ["9. 変更とお問い合わせ","アプリ機能、外部サービス、法的要件の変更に伴い本ポリシーを更新する場合があります。お問い合わせ：hopalt@gmail.com"]]
  },
  "zh-Hant": {
    navFeatures:"遊戲特色",navPrivacy:"隱私權政策",eyebrow:"小手完成的像素遊戲",title:"選擇、輕敲，\n創造自己的世界。",intro:"Super Foam Pixel 把泡棉積木創作的樂趣帶到手機與平板，讓孩子輕鬆玩像素創作。",coming:"Google Play · App Store 上架準備中",templates:"豐富圖案",templatesBody:"從動物、水果、交通工具、情緒、冒險等主題中選擇。",free:"自由創作",freeBody:"用喜歡的顏色自由填滿 8×8 或 10×10 格子。",impact:"趣味工具輕輕敲",impactBody:"選擇橡膠槌、貓掌、機器人拳頭，以及可愛音效與震動。",family:"為孩子與家人設計",familyBody:"提供大尺寸操作區、自由與嚴格模式、色彩提示和作品備份。",local:"作品保存在裝置中",localBody:"不必建立帳號即可遊玩。作品可保存在裝置中，也能匯出成圖片分享。",tablet:"平板呈現更多細節",tabletBody:"大螢幕可使用精細的 16×16 圖案。",privacy:"了解我們如何保護隱私",privacyBody:"應用程式沒有帳號系統，作品預設保存在裝置中。我們清楚說明廣告與選用功能的資料處理。",privacyButton:"閱讀隱私權政策",contact:"聯絡我們",back:"返回首頁",policyTitle:"隱私權政策",updated:"生效日期：2026 年 8 月 31 日",policyIntro:"hopalt（以下稱「開發者」）提供 Super Foam Pixel（套件：com.hopalt.dfblock）。本政策說明使用應用程式時資料的處理方式。",policySections:[
      ["1. 重點摘要","應用程式不提供註冊、登入或使用者帳號功能。開發者不會直接要求或收集姓名、電子郵件、電話號碼、位置、聯絡人、相機或麥克風資料。"],
      ["2. 儲存在裝置中的資料","語言、音樂、提示、遊戲模式、敲擊工具與色彩偏好，以及完成的作品，都儲存在使用者裝置中。開發者無法遠端存取這些資料。"],
      ["3. 廣告與 Kidoz","整合 Kidoz 的 Android 版本可能透過 Kidoz SDK 顯示橫幅廣告。目前 iOS 版本沒有 Kidoz 廣告。Kidoz 提供情境式廣告，而非行為定向廣告。為提供及營運廣告，可能處理國家層級的概略位置、裝置、作業系統與語言資訊、廣告使用資訊及短期隨機工作階段識別碼。依其官方政策，SDK 不收集廣告識別碼。先前發行的版本可能仍包含原有的廣告 SDK。"],
      ["4. 照片、分享與備份","只有在使用者主動選擇時，完成作品才會儲存至照片圖庫或透過系統分享選單傳送。備份檔不會自動上傳至開發者的伺服器。"],
      ["5. 兒童隱私","本應用程式專為包含兒童的家庭設計。開發者不要求兒童輸入個人資料。家長與監護人可以管理裝置中的應用程式資料與匯出檔案。"],
      ["6. 第三方服務","Android 廣告使用 Kidoz；照片儲存、分享及檔案選擇使用 Apple／Google 的系統功能。Kidoz 的資料保存、刪除及隱私權行使方式，請參閱下方官方政策。",{"label":"Kidoz 隱私權政策","url":"https://www.kidoz.net/privacy-policy"}],
      ["7. 保存、刪除與安全","裝置內資料會保留到使用者刪除為止。分享的照片與備份檔則依所選目的地的政策保存。"],
      ["8. 跨境處理","Kidoz 等第三方服務可能在使用者所在國家以外處理資訊，並適用各提供者的隱私保護措施。"],
      ["9. 政策變更與聯絡方式","應用程式功能、外部服務或法律要求變更時，本政策可能更新。聯絡信箱：hopalt@gmail.com"]]
  },
  vi: {
    navFeatures:"Tính năng",navPrivacy:"Quyền riêng tư",eyebrow:"Trò chơi pixel từ đôi tay nhỏ",title:"Chọn, chạm và tạo nên\nthế giới của riêng bé.",intro:"Super Foam Pixel mang niềm vui lắp ghép khối xốp lên điện thoại và máy tính bảng dành cho các nhà sáng tạo nhỏ tuổi.",coming:"Đang chuẩn bị phát hành trên Google Play · App Store",templates:"Nhiều mẫu vẽ",templatesBody:"Chọn động vật, trái cây, xe cộ, cảm xúc, phiêu lưu và nhiều chủ đề khác.",free:"Tự do sáng tạo",freeBody:"Tô lưới 8×8 hoặc 10×10 bằng bất kỳ màu nào bé thích.",impact:"Chạm bằng dụng cụ vui nhộn",impactBody:"Chọn búa, chân mèo, nắm đấm rô-bốt cùng âm thanh và rung đáng yêu.",family:"Thiết kế cho trẻ em và gia đình",familyBody:"Nút bấm lớn, chế độ tự do và chính xác, gợi ý màu cùng sao lưu tác phẩm.",local:"Tác phẩm ở lại trên thiết bị",localBody:"Chơi ngay không cần tài khoản. Lưu tác phẩm trên thiết bị hoặc xuất thành ảnh để chia sẻ.",tablet:"Nhiều chi tiết hơn trên máy tính bảng",tabletBody:"Màn hình lớn mở khóa các mẫu 16×16 chi tiết.",privacy:"Xem cách chúng tôi bảo vệ quyền riêng tư",privacyBody:"Ứng dụng không có hệ thống tài khoản và mặc định lưu tác phẩm trên thiết bị. Quảng cáo và tính năng tùy chọn được giải thích rõ ràng.",privacyButton:"Đọc Chính sách quyền riêng tư",contact:"Liên hệ",back:"Trang chủ",policyTitle:"Chính sách quyền riêng tư",updated:"Có hiệu lực: 31 tháng 8, 2026",policyIntro:"hopalt (“Nhà phát triển”) cung cấp Super Foam Pixel (gói: com.hopalt.dfblock). Chính sách này giải thích cách dữ liệu được xử lý khi sử dụng ứng dụng.",policySections:[
      ["1. Tóm tắt","Ứng dụng không có chức năng đăng ký, đăng nhập hay tài khoản người dùng. Nhà phát triển không trực tiếp yêu cầu hoặc thu thập tên, email, số điện thoại, vị trí, danh bạ, dữ liệu camera hoặc micrô."],
      ["2. Dữ liệu lưu trên thiết bị","Ngôn ngữ, nhạc, gợi ý, chế độ chơi, dụng cụ, tùy chọn màu và tác phẩm đã lưu đều nằm trên thiết bị. Nhà phát triển không thể truy cập từ xa."],
      ["3. Quảng cáo và Kidoz","Các phiên bản Android tích hợp Kidoz có thể hiển thị quảng cáo biểu ngữ qua Kidoz SDK. Phiên bản iOS hiện tại không có quảng cáo Kidoz. Kidoz cung cấp quảng cáo theo ngữ cảnh thay vì theo hành vi. Để phân phối và vận hành quảng cáo, Kidoz có thể xử lý vị trí gần đúng ở cấp quốc gia, thông tin thiết bị, hệ điều hành, ngôn ngữ, hoạt động quảng cáo và mã phiên ngẫu nhiên tồn tại ngắn hạn. Theo chính sách chính thức, SDK không thu thập mã nhận dạng quảng cáo. Các phiên bản đã phát hành trước đây có thể vẫn chứa SDK quảng cáo cũ."],
      ["4. Ảnh, chia sẻ và sao lưu","Chỉ khi người dùng chọn, tác phẩm mới được lưu vào thư viện ảnh hoặc gửi qua bảng chia sẻ hệ thống. Tệp sao lưu không tự động tải lên máy chủ của Nhà phát triển."],
      ["5. Quyền riêng tư của trẻ em","Ứng dụng được thiết kế cho gia đình, bao gồm trẻ em. Nhà phát triển không yêu cầu trẻ nhập thông tin cá nhân. Phụ huynh có thể quản lý dữ liệu và tệp đã xuất trên thiết bị."],
      ["6. Dịch vụ bên thứ ba","Ứng dụng dùng Kidoz cho quảng cáo Android và các tính năng hệ thống của Apple/Google để lưu ảnh, chia sẻ và chọn tệp. Xem chính sách chính thức bên dưới về việc lưu giữ, xóa dữ liệu và thực hiện quyền riêng tư đối với Kidoz.",{"label":"Chính sách quyền riêng tư của Kidoz","url":"https://www.kidoz.net/privacy-policy"}],
      ["7. Lưu giữ, xóa và bảo mật","Dữ liệu trên thiết bị được giữ đến khi người dùng xóa. Ảnh và tệp sao lưu đã chia sẻ được lưu theo chính sách của nơi nhận đã chọn."],
      ["8. Xử lý quốc tế","Các nhà cung cấp bên thứ ba như Kidoz có thể xử lý thông tin ngoài quốc gia của người dùng. Biện pháp bảo vệ quyền riêng tư của từng nhà cung cấp được áp dụng."],
      ["9. Thay đổi và liên hệ","Chính sách có thể được cập nhật khi tính năng, dịch vụ bên ngoài hoặc yêu cầu pháp lý thay đổi. Liên hệ: hopalt@gmail.com"]]
  },
  id: {
    navFeatures:"Fitur",navPrivacy:"Privasi",eyebrow:"Permainan pixel dari tangan kecil",title:"Pilih, ketuk, dan buat\nduniamu sendiri.",intro:"Super Foam Pixel menghadirkan keseruan kerajinan balok busa di ponsel dan tablet untuk kreator cilik.",coming:"Sedang disiapkan untuk Google Play · App Store",templates:"Banyak pola",templatesBody:"Pilih hewan, buah, kendaraan, emosi, petualangan, dan lainnya.",free:"Berkreasi bebas",freeBody:"Isi kotak 8×8 atau 10×10 dengan warna apa pun yang disukai.",impact:"Ketuk dengan alat seru",impactBody:"Pilih palu, kaki kucing, tinju robot, suara lucu, dan getaran.",family:"Dirancang untuk anak dan keluarga",familyBody:"Kontrol besar, mode bebas dan tepat, petunjuk warna, serta cadangan karya tersedia.",local:"Karya tersimpan di perangkat",localBody:"Mulai tanpa akun. Simpan karya di perangkat atau ekspor sebagai gambar untuk dibagikan.",tablet:"Lebih detail di tablet",tabletBody:"Layar besar membuka pola 16×16 yang lebih detail.",privacy:"Lihat cara kami menjaga privasi",privacyBody:"Aplikasi tidak memiliki sistem akun dan menyimpan karya di perangkat secara default. Iklan dan fitur opsional dijelaskan dengan jelas.",privacyButton:"Baca Kebijakan Privasi",contact:"Kontak",back:"Beranda",policyTitle:"Kebijakan Privasi",updated:"Berlaku: 31 Agustus 2026",policyIntro:"hopalt (“Pengembang”) menyediakan Super Foam Pixel (paket: com.hopalt.dfblock). Kebijakan ini menjelaskan cara data diproses saat aplikasi digunakan.",policySections:[
      ["1. Ringkasan","Aplikasi tidak memiliki pendaftaran, login, atau akun pengguna. Pengembang tidak secara langsung meminta atau mengumpulkan nama, email, nomor telepon, lokasi, kontak, data kamera, atau mikrofon."],
      ["2. Data yang tersimpan di perangkat","Bahasa, musik, petunjuk, mode bermain, alat, pilihan warna, dan karya tersimpan berada di perangkat pengguna. Pengembang tidak dapat mengaksesnya dari jarak jauh."],
      ["3. Iklan dan Kidoz","Versi Android yang terintegrasi dengan Kidoz dapat menampilkan iklan banner melalui Kidoz SDK. Versi iOS saat ini tidak memiliki iklan Kidoz. Kidoz menyediakan iklan kontekstual, bukan iklan berbasis perilaku. Untuk menayangkan dan mengoperasikan iklan, Kidoz dapat memproses perkiraan lokasi tingkat negara, informasi perangkat, sistem operasi, bahasa, penggunaan iklan, dan pengenal sesi acak berumur pendek. Menurut kebijakan resminya, SDK tidak mengumpulkan pengenal iklan. Versi yang dirilis sebelumnya mungkin masih menyertakan SDK iklan lama."],
      ["4. Foto, berbagi, dan cadangan","Hanya jika dipilih pengguna, karya dapat disimpan ke galeri foto atau dikirim melalui menu berbagi sistem. File cadangan tidak otomatis diunggah ke server Pengembang."],
      ["5. Privasi anak","Aplikasi dirancang untuk keluarga, termasuk anak-anak. Pengembang tidak meminta anak memasukkan informasi pribadi. Orang tua dapat mengelola data aplikasi dan file ekspor di perangkat."],
      ["6. Layanan pihak ketiga","Aplikasi menggunakan Kidoz untuk iklan Android serta fitur sistem Apple/Google untuk foto, berbagi, dan pemilihan file. Lihat kebijakan resmi di bawah tentang penyimpanan, penghapusan data, dan pelaksanaan hak privasi terkait Kidoz.",{"label":"Kebijakan Privasi Kidoz","url":"https://www.kidoz.net/privacy-policy"}],
      ["7. Penyimpanan, penghapusan, dan keamanan","Data di perangkat disimpan sampai pengguna menghapusnya. Foto dan cadangan yang dibagikan disimpan sesuai kebijakan tujuan yang dipilih."],
      ["8. Pemrosesan internasional","Penyedia pihak ketiga seperti Kidoz dapat memproses informasi di luar negara pengguna. Perlindungan privasi masing-masing penyedia berlaku."],
      ["9. Perubahan dan kontak","Kebijakan dapat diperbarui jika fitur, layanan eksternal, atau persyaratan hukum berubah. Kontak: hopalt@gmail.com"]]
  }
};
